package com.gameover.android.core.common

object PermissionMatrix {
    val resourceKeys = setOf(
        "/dashboard",
        "/users",
        "/users:create",
        "/users:update",
        "/users:status",
        "/users:password",
        "/roles",
        "/roles:update",
        "/plans",
        "/plans:create",
        "/plans:update",
        "/plans:delete",
        "/draws",
        "/draws:create",
        "/draws:update",
        "/draws:delete",
        "/draws:restricted-numbers",
        "/draws/list",
        "/multiplicadores",
        "/multiplicadores:create",
        "/multiplicadores:update",
        "/multiplicadores:delete",
        "/sales",
        "/sales:create",
        "/sales:cancel",
        "/ticket-payments",
        "/ticket-payments:mark-paid",
        "/ticket-payments:revert",
        "/cash-movements",
        "/cash-movements:create",
        "/cash-movements:cancel",
        "/reports",
        "/reports/sales-stats",
        "/reports/balance-breakdown",
        "/reports/sales-by-user",
        "/reports/draw-lists",
        "/reports/commissions",
        "/print-queue"
    )
}
